### ISSUE TITLE
为什么安装的库没问题，总是出现这个报错？

### ISSUE THREAD

**Issue by ZJH970922** [ChenCongGit/RoLabelImg_Transform#3]
Traceback (most recent call last):
  File "RoLabelImg_Transform/get_list.py", line 34, in <module>
    raise ValueError("model only txt_to_xml and xml_to_txt")
ValueError: model only txt_to_xml and xml_to_txt

**Comment by liuhuiCNN** [comment]
> Traceback (most recent call last):
> File "RoLabelImg_Transform/get_list.py", line 34, in
> raise ValueError("model only txt_to_xml and xml_to_txt")
> ValueError: model only txt_to_xml and xml_to_txt

遇到了同样错误，请问你解决了吗？

**Comment by chen-si-jia** [comment]
打开代码文件，将默认路径进行修改，之后直接运行python RoLabelImg_Transform/get_list.py即可。

**Comment by happysnzy** [comment]
请问怎么修改默认路径？ @chen-si-jia
